# Generated by Django 3.1.7 on 2021-05-28 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='additional_information',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='display_name',
        ),
        migrations.AddField(
            model_name='hotel',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='hotel/'),
        ),
        migrations.AddField(
            model_name='room',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='hotel/'),
        ),
    ]
