# Generated by Django 3.1.7 on 2021-06-04 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210602_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='Services',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
