# Generated by Django 3.1.7 on 2021-06-08 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210608_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='payment',
        ),
        migrations.AddField(
            model_name='reservation',
            name='payment_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='trnxid',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
