# Generated by Django 3.1.7 on 2021-06-25 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210608_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('1', 'Premium'), ('2', 'Deluxe'), ('3', 'Economi')], max_length=50),
        ),
    ]
